### ISSUE TITLE
DevelopmentSystemID was null error

### ISSUE THREAD

**Issue by ryouhei8724** [SAP/devops-cm-client#33]
"DevelopmentSystemID was null error" occurred when I tried to execute cmclient 2.0.1 tools as below.

_[root@localhost bin]# ./cmclient -version
2.0.1 : cdae8118b9f6a3d0755c717fe80567cfbd703d72
[root@localhost bin]# ./cmclient -e 'http://sgpssvm534.sin.global.corp.sap:8055/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV' -u i338126 -p **** -t SOLMAN upload-file-to-transport -cID 8000001373 -tID CD1K900002 SCP_CF "/var/lib/docker/volumes/jenkins_home_volume/_data/workspace/changemanagement/tutorial.mtar"
Exception in thread "main" java.lang.IllegalStateException: DevelopmentSystemID was null when retrieving transports for change '8000001373'._

I tried cmclient tools with "dID" option but it did not work as error "Unrecognized option: -dID" .

Release note said this bug was fixed at 2.0.1 release, but it looks not fixing yet.

**Comment by marcusholl** [comment]
Is there any stack trace associated with the failure. Can you provide the stack trace.

Without having more details: What version of solution manager are you using? In case we have 7.2 SP6 or SP7 we should use version `1.0.0` rather than `2.x`

**Comment by ryouhei8724** [comment]
Thank you for your reply.
Our Solman is 7.2 SP6. I'll try cmclient version 1.0.0.

**Comment by ryouhei8724** [comment]
Tried version 1.0.0. I faced another error.
Should I open as new issue?

[root@localhost bin]# ./cmclient -e 'http://sgpssvm534.sin.global.corp.sap:8055/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV' -u i338126 -p **** -t SOLMAN upload-file-to-transport -cID 8000001373 -tID CD1K900002 SCP_CF "/var/lib/docker/volumes/jenkins_home_volume/_data/workspace/changemanagement/tutorial.mtar"
org.apache.olingo.client.api.http.HttpClientException: java.util.concurrent.ExecutionException: org.apache.olingo.client.api.communication.ODataClientErrorException: Runtime error CALL_FUNCTION_SINGLE_LOGIN_REJ has occurred. [HTTP/1.1 400 Bad Request]
	at org.apache.olingo.client.core.communication.request.AbstractODataStreamManager.getHttpResponse(AbstractODataStreamManager.java:128)
	at org.apache.olingo.client.core.communication.request.streamed.ODataMediaEntityUpdateRequestImpl$MediaEntityUpdateStreamManagerImpl.getResponse(ODataMediaEntityUpdateRequestImpl.java:91)
	at org.apache.olingo.client.core.communication.request.streamed.ODataMediaEntityUpdateRequestImpl$MediaEntityUpdateStreamManagerImpl.getResponse(ODataMediaEntityUpdateRequestImpl.java:76)
	at org.apache.olingo.client.core.communication.request.AbstractODataStreamManager.getResponse(AbstractODataStreamManager.java:146)
	at sap.ai.st.cm.plugins.ciintegration.odataclient.CMODataSolmanClient.uploadFileToTransport(CMODataSolmanClient.java:221)
	at sap.prd.cmintegration.cli.UploadFileToTransportSOLMAN$1.apply(UploadFileToTransportSOLMAN.java:115)
	at sap.prd.cmintegration.cli.UploadFileToTransportSOLMAN$1.apply(UploadFileToTransportSOLMAN.java:106)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at sap.prd.cmintegration.cli.TransportRelated.execute(TransportRelated.java:135)
	at sap.prd.cmintegration.cli.TransportRelatedSOLMAN.execute(TransportRelatedSOLMAN.java:68)
	at sap.prd.cmintegration.cli.UploadFileToTransportSOLMAN.main(UploadFileToTransportSOLMAN.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sap.prd.cmintegration.cli.Commands.main(Commands.java:302)
	at sap.prd.cmintegration.cli.ExitWrapper.main(ExitWrapper.java:15)
Caused by: java.util.concurrent.ExecutionException: org.apache.olingo.client.api.communication.ODataClientErrorException: Runtime error CALL_FUNCTION_SINGLE_LOGIN_REJ has occurred. [HTTP/1.1 400 Bad Request]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.apache.olingo.client.core.communication.request.AbstractODataStreamManager.getHttpResponse(AbstractODataStreamManager.java:125)
	... 16 more
Caused by: org.apache.olingo.client.api.communication.ODataClientErrorException: Runtime error CALL_FUNCTION_SINGLE_LOGIN_REJ has occurred. [HTTP/1.1 400 Bad Request]
	at org.apache.olingo.client.core.communication.header.ODataErrorResponseChecker.checkResponse(ODataErrorResponseChecker.java:75)
	at org.apache.olingo.client.core.communication.request.AbstractRequest.checkResponse(AbstractRequest.java:54)
	at org.apache.olingo.client.core.communication.request.AbstractODataRequest.doExecute(AbstractODataRequest.java:310)
	at org.apache.olingo.client.core.communication.request.streamed.AbstractODataStreamedRequest.access$200(AbstractODataStreamedRequest.java:51)
	at org.apache.olingo.client.core.communication.request.streamed.AbstractODataStreamedRequest$1.call(AbstractODataStreamedRequest.java:108)
	at org.apache.olingo.client.core.communication.request.streamed.AbstractODataStreamedRequest$1.call(AbstractODataStreamedRequest.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by marcusholl** [comment]
> Should I open as new issue?

Thanks for asking. From the pure doctrines point of view we should open a new issue. But never mind, we can continue with this issue here.

This is nothing where I can help immediately.  I will contact some colleagues and come back (or an other colleague will provide the answer directly here).

**Comment by marcusholl** [comment]
I'm proxying a response from another colleague here:

> This appears to be an issue with the trusted system RFC to the managed system (or the SolMan itself if is the communication system).

In order to resolve the issue the colleague suggests to check `ST22` for dumps related to this error regarding the trusted RFC connection and check the destination and the users credentials/authorization.

If that does not help please open a ticket under `SV-SMG-CM`.

**Comment by ryouhei8724** [comment]
Thank you very much! 
I understood this is net weaver issue.
I try to check it from st22.

**Comment by marcusholl** [comment]
Is this issue resolved in the meantime?

**Comment by radsoulbeard** [comment]
No response for more than 3 months -> closed
